#!/bin/bash
#
# Configure Moodle's cron inside the DDEV web container so that scheduled tasks
# and adhoc tasks (course backup/restore, notifications, search indexing…) run
# on their own — which is what makes async behaviour testable in a dev install.
#
# Run as a post_custom_script by moodle_ddev.sh. Arguments are the toolkit's
# standard DEFAULT_ARGS:
#   $1 project_dir     host path of the DDEV approot (mounted at /var/www/html)
#   $2 MOODLE_DOC_ROOT ./moodle, or ./moodle/public on Moodle 5.1+
#   $3 DDEV_DESCRIBE   `ddev describe -j` output
#   $4 moodle_version  $5 php_version  $6 db_type
#
# Nothing here touches the *host* crontab: the earlier version of this script
# piped into `crontab -` while running on the host, which edited the developer's
# own crontab and left the container without any cron at all.

set -uo pipefail

project_dir="${1:-$PWD}"
doc_root="${2:-./moodle}"

echo "🔧 Setting up Moodle cron in the DDEV web container..."

# ---------------------------------------------------------------------------
# Locate Moodle. The docroot moves to ./moodle/public on 5.1+, but admin/cli
# stays at the *code* root — so the docroot is not the path to cron.php.
# ---------------------------------------------------------------------------
moodle_rel="${doc_root#./}"          # moodle | moodle/public
moodle_rel="${moodle_rel%/public}"   # moodle
moodle_rel="${moodle_rel:-moodle}"

if [[ ! -f "${project_dir}/${moodle_rel}/admin/cli/cron.php" ]]; then
    echo "⚠️  No Moodle CLI found at ${project_dir}/${moodle_rel}/admin/cli/cron.php"
    echo "    Skipping cron setup."
    return 0 2>/dev/null || exit 0
fi

container_cron_php="/var/www/html/${moodle_rel}/admin/cli/cron.php"
echo "   Moodle CLI: ${container_cron_php}"

cd "$project_dir" || { echo "❌ Cannot cd to ${project_dir}"; return 1 2>/dev/null || exit 1; }

cron_log="/var/log/moodle-cron.log"

# ---------------------------------------------------------------------------
# 1. Make sure the web image actually has cron.
#
# DDEV's webserver image does ship cron, but it is never started — so this
# layer is a no-op on current images and a safety net on any image that drops
# the package. Kept in its own Dockerfile.<name> because web-build/Dockerfile
# already belongs to the locale layer (see sub/dockerfiles.sh) and DDEV
# concatenates every Dockerfile* in that directory.
# ---------------------------------------------------------------------------
mkdir -p .ddev/web-build
cat > .ddev/web-build/Dockerfile.cron <<'EOF'
# Moodle cron: guarantee the cron package exists in the web image.
# The schedule itself is installed at container start by
# .ddev/web-entrypoint.d/moodle-cron.sh, so that it can resolve the
# project's web user (DDEV names it after the host user) at runtime.
RUN set -eu; \
    command -v cron >/dev/null 2>&1 || { \
        apt-get update; \
        apt-get install -y --no-install-recommends cron; \
        apt-get clean; rm -rf /var/lib/apt/lists/*; \
    }
EOF

# ---------------------------------------------------------------------------
# 2. Install the schedule + start the daemon on every container start.
#
# web-entrypoint.d/*.sh is DDEV's documented startup hook and runs before
# php-fpm. Doing it here rather than baking it into the image means it survives
# `ddev restart`, `ddev stop`, and image rebuilds, and it can read the web
# user's real name with `id -un` instead of guessing it at build time.
# ---------------------------------------------------------------------------
mkdir -p .ddev/web-entrypoint.d
cat > .ddev/web-entrypoint.d/moodle-cron.sh <<EOF
#!/bin/bash
# Generated by post_custom_scripts/setup_moodle_cron.sh — safe to delete if you
# do not want Moodle cron running every minute in this project.
set -u

CRON_USER="\$(id -un)"

# Run cron.php as the web user, never as root: root-owned files appearing in
# moodledata are a classic cause of later "cannot write to dataroot" errors.
# A cron.d fragment must be 0644 and its name must not contain a dot.
sudo tee /etc/cron.d/moodle-cron >/dev/null <<EOT
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
* * * * * \${CRON_USER} /usr/bin/php ${container_cron_php} >>${cron_log} 2>&1
EOT
sudo chmod 0644 /etc/cron.d/moodle-cron

sudo touch ${cron_log}
sudo chown "\${CRON_USER}" ${cron_log}

sudo service cron start >/dev/null 2>&1 || sudo /usr/sbin/cron
EOF
chmod +x .ddev/web-entrypoint.d/moodle-cron.sh

echo "   ✅ .ddev/web-build/Dockerfile.cron"
echo "   ✅ .ddev/web-entrypoint.d/moodle-cron.sh"

# ---------------------------------------------------------------------------
# 3. Apply to the container that is running right now.
#
# moodle_ddev.sh restarts DDEV after the post scripts, which is when the
# entrypoint above takes over. Running it once here means cron is live
# immediately and — more importantly — that this script can verify its own
# work instead of just writing files and hoping.
# ---------------------------------------------------------------------------
if ! ddev describe >/dev/null 2>&1; then
    echo "ℹ️  Project is not running; cron starts with the next 'ddev start'."
    return 0 2>/dev/null || exit 0
fi

# Use /mnt/ddev_config, not /var/www/html/.ddev: DDEV bind-mounts .ddev there,
# so the file just written is visible immediately. The /var/www/html copy is
# mutagen-synced and lags behind on a project the size of Moodle — reading it
# here raced the sync and failed with "No such file or directory".
echo "🔄 Applying cron to the running web container..."
if ! ddev exec bash /mnt/ddev_config/web-entrypoint.d/moodle-cron.sh; then
    echo "⚠️  Could not configure cron in the running container."
    echo "    It will be retried automatically on the next 'ddev restart'."
    return 0 2>/dev/null || exit 0
fi

# ------- Verify: daemon up, schedule installed, cron.php runnable -------
ok=true

if ddev exec pgrep -x cron >/dev/null 2>&1; then
    echo "✅ cron daemon running"
else
    echo "❌ cron daemon is not running"
    ok=false
fi

if ddev exec test -f /etc/cron.d/moodle-cron >/dev/null 2>&1; then
    echo "✅ schedule installed at /etc/cron.d/moodle-cron:"
    ddev exec grep -v '^[A-Z]*=' /etc/cron.d/moodle-cron 2>/dev/null | sed 's/^/     /'
else
    echo "❌ /etc/cron.d/moodle-cron missing"
    ok=false
fi

# Proves the *path* is right — a wrong path was the other half of the old bug,
# and cron would have failed silently every minute.
if ddev exec php "$container_cron_php" --help >/dev/null 2>&1; then
    echo "✅ ${container_cron_php} is executable by PHP"
else
    echo "❌ PHP cannot run ${container_cron_php}"
    ok=false
fi

if [[ "$ok" == true ]]; then
    echo "✅ Moodle cron active — runs every minute."
    echo "   Watch it:  ddev exec tail -f ${cron_log}"
    echo "   Run once:  ddev exec php ${moodle_rel}/admin/cli/cron.php"
else
    echo "⚠️  Moodle cron setup incomplete — see the failures above."
fi
